# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: maninfocar
replicaCount: 1
strategyType: RollingUpdate
# `serviceAccountName` is deprecated in favor of `serviceAccount.name`
serviceAccountName:
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: IfNotPresent
  secrets:
    - name: gitlab-registry-torr-tsdc-maninfocar
extraLabels: {}
terminationGracePeriodSeconds: 120
lifecycle: 
  preStop:
    httpGet:
      path: ejb-timer-service-ws/resources/timers/shutdown
      port: 8080
          
  #  exec:
  #    command: ["/bin/sh", "-c", "${HOME_DIR}/shutdownInstance.sh"]
podAnnotations: {}
nodeSelector: {}
affinity: {}
tolerations: []
application:
  track: canary
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
gitlab:
  app:
  env:
  envName:
  envURL:
  projectID:
service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url: http://my.host.com/
  additionalHosts:
  commonName:
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  path: "/"
  tls:
    enabled: true
    acme: true
    secretName: ""
    useDefaultSecret: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/target: "lb-01.internal.torroca.com"
  modSecurity:
    enabled: false
    secRuleEngine: "DetectionOnly"
    # secRules:
    #   - variable: ""
    #     operator: ""
    #     action: ""
  canary:
    weight:
prometheus:
  metrics: true
livenessProbe:
  path: "/"
  initialDelaySeconds: 5
  timeoutSeconds: 1
  failureThreshold: 6
  periodSeconds: 10
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/"
  initialDelaySeconds: 5
  timeoutSeconds: 1
  failureThreshold: 6
  periodSeconds: 10
  scheme: "HTTP"
  probeType: "httpGet"
startupProbe:
  enabled: true
  path: "/"
  initialDelaySeconds: 60
  timeoutSeconds: 1
  failureThreshold: 6
  periodSeconds: 10
  scheme: "HTTP"
  probeType: "httpGet"
  
postgresql:
  managed: false
  managedClassSelector:
    #   matchLabels:
    #     stack: gitlab (This is an example. The labels should match the labels on the CloudSQLInstanceClass)

resources:
  limits:
#    cpu: 100m
    memory: 1Gi
  requests: 
#    cpu: 100m
    memory: 1Gi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1

## Configure NetworkPolicy
## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
#
networkPolicy:
  enabled: false
  spec:
    podSelector:
      matchLabels: {}
    ingress:
    - from:
      - podSelector:
          matchLabels: {}
      - namespaceSelector:
          matchLabels:
            app.gitlab.com/managed_by: gitlab

ciliumNetworkPolicy:
  enabled: false
  alerts:
    enabled: false
  spec:
    endpointSelector: {}
    ingress:
    - fromEndpoints:
      - matchLabels:
          app.gitlab.com/managed_by: gitlab

serviceAccount:
  name:
  annotations: {}
  createNew: false

workers: 
  #worker:
  #   replicaCount: 1
  #  terminationGracePeriodSeconds: 60
  #   command:
  #   - /bin/herokuish
  #   - procfile
  #   - start
  #   - worker
  #   nodeSelector: {}
  #   tolerations: []
  #   livenessProbe:
  #     path: "/"
  #     initialDelaySeconds: 15
  #     timeoutSeconds: 15
  #     scheme: "HTTP"
  #     probeType: "httpGet"
  #   readinessProbe:
  #     path: "/"
  #     initialDelaySeconds: 5
  #     timeoutSeconds: 3
  #     scheme: "HTTP"
  #     probeType: "httpGet"
  #   lifecycle:
  #     preStop:
  #       exec:
  #         command: ["/bin/sh", "-c", "sleep 10"]
  #   preStopCommand:
  #   - /bin/herokuish
  #   - procfile
  #   - start
  #   - stop_worker
customResources:
#  - apiVersion: monitoring.coreos.com/v1
#    kind: ServiceMonitor
#    metadata:
#      name: "{{ .Values.gitlab.env }}-torrbank"
#      labels:
#        track: "{{ .Values.application.track }}"  
#        release: prometheus-operator
#    spec:
#      namespaceSelector:
#        matchNames:
#          - "{{ .Release.Namespace }}"
#      selector:
#        matchLabels:
#          app: "{{ .Values.gitlab.env }}"
#          release: "{{ .Values.gitlab.env }}"
#          track: "{{ .Values.application.track }}"
#      endpoints:
#        - targetPort: 8080
#          path: "/metrics"
#          interval: 10s  
